### ISSUE TITLE
seedsをぶっこむ

### ISSUE THREAD

**Issue by cnosuke** [cnosuke/ton9#16]

**Comment by moosan63** [comment]
やります。

**Comment by moosan63** [comment]
seedつくりました。
rake db:seed:user

moosan, cnosuke, wishid, rkmathi, opentaka
っていうユーザーが作られてメールアドレスは
email = USER_NAME@example.com
pw     = foofoo 
で、ログインできます。
ドキュメントも7つくらい入った状態で表示されます。
