### ISSUE TITLE
お手数ですがassignから外してください

### ISSUE THREAD

**Issue by lohn** [cnosuke/ton9#35]
@cnosuke お久しぶりです！
お手数ですが下記issueからassignを外してほしいです (自分で解除できなかった・・・)

https://github.com/cnosuke/ton9/issues/13
https://github.com/cnosuke/ton9/issues/15

よろしくお願いしますー。

**Comment by cnosuke** [comment]
おっと、お久しぶりです！！！了解です 🙆

**Comment by lohn** [comment]
ありがとうございます！！！
